name: flutter_icon_park
description: "This is the Flutter implementation of the ByteDance IconPark icon library, a set of SVG-based icons. It supports multiple color modes."
version: 0.0.1
homepage: https://github.com/xioxin/flutter_icon_park
repository: https://github.com/xioxin/flutter_icon_park
issue_tracker: https://github.com/xioxin/flutter_icon_park/issues

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - icons
  - svg
